[phases.setup]
nixPkgs = ['php82', 'nodejs-18_x']

[phases.install]
cmds = [
    'npm install',
    'npm run build'
]

[phases.build]
cmds = [
    'cp -r backend/* .',
    'cp -r dist/* .',
    'ls -la'
]

[start]
cmd = 'php -S 0.0.0.0:$PORT -t .'