[phases.setup]
nixPkgs = ['php82', 'nodejs-18_x']

[phases.install]
cmds = [
    'npm install'
]

[phases.build]
cmds = [
    'cp index.dev.html index.html',
    'npm run build',
    'rm index.html',
    'cp -r backend/* .',
    'cp -r dist/* .',
    'echo "Final files:"',
    'ls -la'
]

[start]
cmd = 'php -S 0.0.0.0:$PORT -t .'